In [11]:
# -*- coding: utf-8 -*-
"""
 

@author: Umme Rubaiyat Chowdhury
"""

'\n \n\n@author: Umme Rubaiyat Chowdhury\n'

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
#importing SVM model
from sklearn.svm import SVC

In [3]:
#Importing the Dataset from url
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
 

In [4]:
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)
irisdata 

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
X= irisdata.drop("Class", axis=1)
y= irisdata['Class']

In [6]:
X_train,X_test, y_train, y_test= train_test_split(X,y,test_size=0.25, random_state=123)

In [7]:
##Gaussian Kernel
#To use Gaussian kernel, you have to specify 'rbf' as value for the Kernel parameter of the SVC class.
model = SVC(kernel = "rbf")
model.fit(X_train, y_train)

SVC()

In [8]:
#Prediction 
y_pred = model.predict(X_test)

In [9]:
#Evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0  8  0]
 [ 0  1 13]]


In [10]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       0.89      1.00      0.94         8
 Iris-virginica       1.00      0.93      0.96        14

       accuracy                           0.97        38
      macro avg       0.96      0.98      0.97        38
   weighted avg       0.98      0.97      0.97        38

